[deploy]
buildCommand = "pip install -r requirements.txt"
startCommand = "gunicorn admin_dashboard:app --bind 0.0.0.0:$PORT & python bot.py"

[build]
builder = "nixpacks"

[variables]
BOT_TOKEN = "your-bot-token-here"
